###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "George Mendel",
    "age": 81,
    "email": "georgemendel@email.com"
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/63a5bd7e40240403f9b04ece HTTP/1.1


###
PUT http://localhost:9000/api/users/63a5bd7e40240403f9b04ece HTTP/1.1
Content-Type: application/json

{
    "name": "George Mendel",
    "age": 81,
    "email": "georgemendel@email.com"
}


###
DELETE http://localhost:9000/api/users/63a5bc9ad5832f634210bf9f HTTP/1.1

